Add GCP IoT Core WiFi, GSM, and NB examples
arduino/ArduinoCloudProviderExamples pull request #2
Opened 2019-03-14 19:40 UTC by sandeepmistry

2019-03-15 07:57 UTC, gvarisco approved these changes
Awesome work, Sandeep. LGTM.

2019-03-16 03:39 UTC, per1234 requested changes

2019-03-16 03:39 UTC, per1234 commented on examples/Google Cloud Platform IoT Core/GCP_IoT_Core_GSM/GCP_IoT_Core_GSM.ino
> +  "/devices/{deviceId}/commands/# topics.
```suggestion
  "/devices/{deviceId}/commands/#" topics.
```

2019-03-16 03:39 UTC, per1234 commented on examples/Google Cloud Platform IoT Core/GCP_IoT_Core_GSM/GCP_IoT_Core_GSM.ino
> +  Serial.print("Attempting to MQTT broker: ");
```suggestion
  Serial.print("Attempting to connect to MQTT broker: ");
```

2019-03-16 03:39 UTC, per1234 commented on examples/Google Cloud Platform IoT Core/GCP_IoT_Core_GSM/arduino_secrets.h
> +#define SECRET_GPRS_APN      "GPRS_APN" // replace your GPRS APN
```suggestion
#define SECRET_GPRS_APN      "GPRS_APN" // replace with your GPRS APN
```

2019-03-16 03:39 UTC, per1234 commented on examples/Google Cloud Platform IoT Core/GCP_IoT_Core_NB/GCP_IoT_Core_NB.ino
> +  "/devices/{deviceId}/commands/# topics.
```suggestion
  "/devices/{deviceId}/commands/#" topics.
```

2019-03-16 03:39 UTC, per1234 commented on examples/Google Cloud Platform IoT Core/GCP_IoT_Core_NB/GCP_IoT_Core_NB.ino
> +  Serial.print("Attempting to MQTT broker: ");
```suggestion
  Serial.print("Attempting to connect to MQTT broker: ");
```

2019-03-16 03:39 UTC, per1234 commented on examples/Google Cloud Platform IoT Core/GCP_IoT_Core_WiFi/GCP_IoT_Core_WiFi.ino
> +  "/devices/{deviceId}/commands/# topics.
```suggestion
  "/devices/{deviceId}/commands/#" topics.
```

2019-03-16 03:39 UTC, per1234 commented on examples/Google Cloud Platform IoT Core/GCP_IoT_Core_WiFi/GCP_IoT_Core_WiFi.ino
> +  Serial.print("Attempting to MQTT broker: ");
```suggestion
  Serial.print("Attempting to connect to MQTT broker: ");
```

2019-03-19 11:56 UTC, Rocketct commented
tested the example, wifi and gsm and works.

2019-03-19 11:57 UTC, Rocketct approved these changes

2019-03-19 14:33 UTC, merged